version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - wordle-network

  auth_db:
    container_name: auth-db
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    ports:
      - '5430:5432'
    volumes:
      #      - /Users/konstantinkirilenko/Desktop/slp/wordle/wordle-micro:/docker-entrypoint-initdb.d
      - ./wordle-micro/auth-service:/docker-entrypoint-initdb.d
      - pg_auth:/var/lib/postgresql/data
    networks:
      - wordle-network

  wordle_db:
    container_name: wordle_db
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wordle_db
    ports:
      - '5432:5432'
    volumes:
      #      - /Users/konstantinkirilenko/Desktop/slp/wordle/wordle-micro:/docker-entrypoint-initdb.d
      - ./wordle-micro/game-service:/docker-entrypoint-initdb.d
      - pg_wordle:/var/lib/postgresql/data
    networks:
      - wordle-network

  eureka-server:
    container_name: eureka-server
    restart: always
    build: wordle-micro/eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - wordle_db
    links:
      - wordle_db
    environment:
      SERVER_PORT: "8761"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
      JWT_SECRET: 'b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e'
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_VK_CLIENTID:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_VK_CLIENTSECRET:
      SPRING_R2DBC_URL: 'r2dbc:postgresql://wordle_db/wordle_db'
      SPRING_R2DBC_USERNAME: 'postgres'
      SPRING_R2DBC_PASSWORD: 'postgres'
    networks:
      - wordle-network

  auth-service:
    container_name: auth-service
    restart: always
    build: wordle-micro/auth-service
    ports:
      - "8084:8084"
    depends_on:
      - wordle_db
      - eureka-server
    links:
      - wordle_db
    environment:
      SERVER_PORT: "8084"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
      JWT_SECRET: 'b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e'
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_VK_CLIENTID: '52428023'
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_VK_CLIENTSECRET: '7Ol7NuJg5up6R5ggteKM'
      SPRING_R2DBC_URL: 'r2dbc:postgresql://auth_db/auth_db'
      SPRING_R2DBC_USERNAME: 'postgres'
      SPRING_R2DBC_PASSWORD: 'postgres'
    networks:
      - wordle-network

  api-gateway:
    container_name: api-gateway
    restart: always
    build: wordle-micro/api-gateway
    ports:
      - "80:80"
    depends_on:
      - wordle_db
      - eureka-server
      - auth-service
    links:
      - wordle_db
    environment:
      SERVER_PORT: "80"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
      JWT_SECRET: 'b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e'
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_VK_CLIENTID: '52428023'
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_VK_CLIENTSECRET: '7Ol7NuJg5up6R5ggteKM'
      SPRING_R2DBC_URL: 'r2dbc:postgresql://auth_db/auth_db'
      SPRING_R2DBC_USERNAME: 'postgres'
      SPRING_R2DBC_PASSWORD: 'postgres'
    networks:
      - wordle-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
    ports:
      - "9092:9092"
    networks:
      - wordle-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - wordle-network


  kafka-connector:
    image: confluentinc/cp-kafka-connect:latest
    container_name: kafka-connector
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - zookeeper
      - auth_db
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "quickstart-avro"
      CONNECT_CONFIG_STORAGE_TOPIC: "quickstart-avro-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "quickstart-avro-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "quickstart-avro-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_LOG4J_ROOT_LOGLEVEL: DEBUG
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
    volumes:
      - ./wordle-micro/jars:/usr/share/confluent-hub-components
    networks:
      - wordle-network

  connector-script:
    image: alpine:3.14
    ports:
      - "8090:8090"
    depends_on:
      - kafka
      - kafka-connector
    command: >
      sh -c "apk update && apk add --no-cache curl && curl -X POST -H 'Content-Type: application/json' --data '{
        \"name\": \"postgres-source\",
        \"config\": {
          \"connector.class\": \"io.confluent.connect.jdbc.JdbcSourceConnector\",
          \"tasks.max\": \"1\",
          \"connection.url\": \"jdbc:postgresql://auth_db:5432/auth_db?user=postgres&password=postgres\",
          \"topic.prefix\": \"auth_\",
          \"poll.interval.ms\": \"1000\",
          \"mode\": \"incrementing\",
          \"incrementing.column.name\": \"id\",
          \"table.whitelist\": \"users\"
        }
      }' http://kafka-connector:8083/connectors"
    networks:
      - wordle-network

  game-service:
    container_name: game-service
    restart: always
    build: wordle-micro/game-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - wordle_db
      - eureka-server
    links:
      - wordle_db
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
      SERVER_PORT: "8082"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
      SPRING_R2DBC_URL: 'r2dbc:postgresql://wordle_db/wordle_db'
      SPRING_R2DBC_USERNAME: 'postgres'
      SPRING_R2DBC_PASSWORD: 'postgres'
    networks:
      - wordle-network

networks:
  wordle-network:
    driver: bridge

volumes:
  pg_wordle:
  pg_auth: